<h1 dir=rtl align=center style="line-height:200%;font-family:vazir;color:#0099cc">
<font face="vazir" color="#0099cc">
Title Categorizer
</font>
</h1>

<p dir=rtl style="direction: rtl; text-align: justify; line-height:200%; font-family:vazir; font-size:medium">
<font face="vazir" size=3>
در این پروژه می خواهیم با استفاده از داده های وبسایت ترب مدلی بسازیم که بتواند با دریافت توضیحات یک محصول، دسته‌بندی آن را پیش‌بینی کند. قصد داریم با استفاده از داده‌های متنی مرتبط با یک محصول همچون عنوان آن برای تشخیص دسته‌بندی استفاده کنیم. با استفاده از چنین مدلی حتی اگر تصویری برای محصول ثبت نشده باشد نیز قادر به دسته‌بندی آن هستیم.
</font>
</p>

<h2 dir=rtl align=right style="line-height:200%;font-family:vazir;color:#0099cc">
<font face="vazir" color="#0099cc">
مجموعه‌داده
</font>
</h2>

<p dir=rtl style="direction: rtl; text-align: justify; line-height:200%; font-family:vazir; font-size:medium">
<font face="vazir" size=3> فایل <code>torob_train.csv</code> شامل اطلاعاتی درباره‌ی تعدادی از محصولات لیست‌شده در این وب‌سایت بوده و شرح هرکدام از ستون‌های آن در جدول زیر آمده است. </font>
</p>

<center>
<div dir=rtl style="direction: rtl;line-height:200%;font-family:vazir;font-size:medium">
<font face="vazir" size=3>

| <b>نام ستون</b> | <b>توضیحات</b> |
| :---: | :---: |
| <code>name1</code> | عنوان اصلی محصول (معمولاً فارسی) |
| <code>name2</code> | عنوان دوم/اختیاری محصول (معمولاً انگلیسی) |
| <code>cat_id</code> | شناسه‌ی دسته‌ی اصلی محصول |

</font>
</div>
</center>

<p dir=rtl style="direction: rtl; text-align: justify; line-height:200%; font-family:vazir; font-size:medium">
<font face="vazir" size=3>
دسته‌بندی‌های این محصولات و شناسه‌ی هر کدام در جدول زیر آمده است:‌
</font>
</p>

<center>
<div dir=rtl style="direction: rtl;line-height:200%;font-family:vazir;font-size:medium">
<font face="vazir" size=3>

| <b>شناسه‌ی دسته</b> | <b>عنوان دسته</b> |
| :---: | :---: |
| <code>0</code> | کاپشن، بارانی و پالتو مردانه |
| <code>1</code> | سویشرت و هودی مردانه |
| <code>2</code> | ساعت مچی عقربه‌ ای و دیجیتالی |
| <code>3</code> | ساعت دیواری، رومیزی و تزیینی |
| <code>4</code> | لوازم جانبی ساعت معمولی و هوشمند |
| <code>5</code> | سویشرت و هودی خردسال و نوجوان |
| <code>6</code> | کاپشن و پالتو خردسال و نوجوان |
| <code>7</code> | سویشرت ورزشی مردانه |
| <code>8</code> | سویشرت و شلوار ورزشی مردانه |
| <code>9</code> | ساک و چرخ خرید |
| <code>10</code> | چمدان و ساک |

</font>
</div>
</center>

In [47]:
import pandas as pd
import numpy as np
import keras

In [48]:
# Reading/Loading the dataset files
train = pd.read_csv('torob_train.csv')
test = pd.read_csv('torob_test.csv')
train

,name1,name2,cat_id
0,کاپشن کوهنوردی پر سنگین نورث فیس,NaN,0
1,پالتو خزدار مردانه مارک اصلی,NaN,0
2,کاپشن مردانه مدل Bako,NaN,0
3,کاپشن سالامون salomon پارچه گورتکس کره ای اعلا...,NaN,0
4,کاپشن‌‌‌ نظامی‌‌‌ آمریکایی‌‌‌ سبز,NaN,0
...,...,...,...
8817,ساک پارچه ای I have spoken,NaN,10
8818,ساک دستی بیسراک Bisrak کد 1172,NaN,10
8819,ساک طرحدار پارچه ای,NaN,10
8820,کیف باشگاه پوما ا puma | 31349075,puma | 31349075,10


In [ ]:
test

,name1,name2
0,بگ پارچه ای دو رنگ چاپ,NaN
1,بادگیر کلاهدار ورزشی فرانسه France windrunner,NaN
2,ساعت دیواری هندسی,NaN
3,ساک ورزشی Nike مدل N20627,NaN
4,ساعت فلزی,NaN
...,...,...
1196,ست گرمکن مردانه Versace | 74GAA3.FS063.G89,NaN
1197,پالتو مردانه مشکی کد 18225 ا Black men's coat ...,Black men's coat code 18225
1198,بند مدل Braided Solo Loop M مناسب برای اپل واچ...,Braided Solo Loop M strap suitable for Apple W...
1199,ساک ورزشی CrossGear مدل SA-9956 ا Sports bag C...,Sports bag CrossGear model SA-9956


In [49]:
import pandas as pd
from sklearn.preprocessing import OneHotEncoder

X = train[['name1', 'name2']]
y = train['cat_id']
y = pd.DataFrame(y, columns=['cat_id'])

# Initialize the OneHotEncoder
encoder = OneHotEncoder(sparse_output=False)

# Fit and transform the column
encoded = encoder.fit_transform(y[['cat_id']])

# Convert to DataFrame with the correct shape
y = pd.DataFrame(encoded, columns=encoder.get_feature_names_out(['cat_id']))

In [ ]:
X

,name1,name2
0,کاپشن کوهنوردی پر سنگین نورث فیس,NaN
1,پالتو خزدار مردانه مارک اصلی,NaN
2,کاپشن مردانه مدل Bako,NaN
3,کاپشن سالامون salomon پارچه گورتکس کره ای اعلا...,NaN
4,کاپشن‌‌‌ نظامی‌‌‌ آمریکایی‌‌‌ سبز,NaN
...,...,...
8817,ساک پارچه ای I have spoken,NaN
8818,ساک دستی بیسراک Bisrak کد 1172,NaN
8819,ساک طرحدار پارچه ای,NaN
8820,کیف باشگاه پوما ا puma | 31349075,puma | 31349075


In [ ]:
y

,cat_id_0,cat_id_1,cat_id_2,cat_id_3,cat_id_4,cat_id_5,cat_id_6,cat_id_7,cat_id_8,cat_id_9,cat_id_10
0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
1,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
2,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
3,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
4,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
...,...,...,...,...,...,...,...,...,...,...,...
8817,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0
8818,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0
8819,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0
8820,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0


<h2 dir=rtl align=right style="line-height:200%;font-family:vazir;color:#0099cc">
<font face="vazir" color="#0099cc">
مدل‌سازی
</font>
</h2>

In [50]:
from tensorflow.keras.layers import TextVectorization
WINDOW_LEN = 500

# Initialize TextVectorization layer
vectorizer = TextVectorization(ngrams=2,output_sequence_length=WINDOW_LEN)
vectorizer.adapt(X['name1'])

# Transform the text data into token sequences
X = vectorizer(X['name1']).numpy()

test = vectorizer(test['name1']).numpy()

# Vocabulary size
VOCAB_SIZE = vectorizer.vocabulary_size()

print(f"Vocab size: {VOCAB_SIZE}")

X

Vocab size: 35238


array([[   5,  384,  469, ...,    0,    0,    0],
       [  93,  391,    3, ...,    0,    0,    0],
       [   5,    3,    4, ...,    0,    0,    0],
       ...,
       [  19, 1089,   39, ...,    0,    0,    0],
       [  35,  629,  214, ...,    0,    0,    0],
       [  27,  248, 1108, ...,    0,    0,    0]])

In [ ]:
test

array([[  108,    39,    14, ...,     0,     0,     0],
       [  177,   119,     6, ...,     0,     0,     0],
       [    2,    24, 13112, ...,     0,     0,     0],
       ...,
       [   31,     4,  5074, ...,     0,     0,     0],
       [   19,     6,     1, ...,     0,     0,     0],
       [    7,     6,    90, ...,     0,     0,     0]])

In [51]:
from sklearn.model_selection import train_test_split

X_train, X_valid, y_train, y_valid = train_test_split(X, y, test_size = 0.1)

In [ ]:
y_train

,cat_id_0,cat_id_1,cat_id_2,cat_id_3,cat_id_4,cat_id_5,cat_id_6,cat_id_7,cat_id_8,cat_id_9,cat_id_10
2133,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
3824,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0
4966,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0
3483,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0
6078,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0
...,...,...,...,...,...,...,...,...,...,...,...
670,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
5373,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0
4972,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0
7358,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0


In [ ]:
X_train

array([[    2,  3108,     4, ...,     0,     0,     0],
       [   31,   164,   855, ...,     0,     0,     0],
       [    5,   161,   205, ...,     0,     0,     0],
       ...,
       [ 3780,    20,   585, ...,     0,     0,     0],
       [   19,    34,  1263, ...,     0,     0,     0],
       [    8, 11207,   585, ...,     0,     0,     0]])

In [55]:
BATCH_SIZE = 64
EMB_SIZE = 300

model = keras.Sequential()
model.add(keras.layers.Input(batch_shape=(BATCH_SIZE, WINDOW_LEN), dtype='int32'))
model.add(keras.layers.Embedding(VOCAB_SIZE, EMB_SIZE, name='embedding'))
model.add(keras.layers.LSTM(200, return_sequences=True, name='lstm', dropout=0.2))
model.add(keras.layers.GlobalMaxPool1D())
model.add(keras.layers.Dropout(0.2))
model.add(keras.layers.Dense(11, activation='softmax'))

model.compile(optimizer='adam', loss='categorical_crossentropy', metrics=['accuracy'])

In [56]:
epochs = 10
batch_size = 128 
history = model.fit(X_train, y_train, epochs = epochs, batch_size = batch_size, validation_data=(X_valid,y_valid)) # TODO

Epoch 1/10
63/63 ━━━━━━━━━━━━━━━━━━━━ 269s 4s/step - accuracy: 0.4171 - loss: 2.0174 - val_accuracy: 0.8743 - val_loss: 0.3860
Epoch 2/10
63/63 ━━━━━━━━━━━━━━━━━━━━ 314s 4s/step - accuracy: 0.9282 - loss: 0.2541 - val_accuracy: 0.9513 - val_loss: 0.1621
Epoch 3/10
63/63 ━━━━━━━━━━━━━━━━━━━━ 261s 4s/step - accuracy: 0.9783 - loss: 0.0862 - val_accuracy: 0.9547 - val_loss: 0.1496
Epoch 4/10
63/63 ━━━━━━━━━━━━━━━━━━━━ 263s 4s/step - accuracy: 0.9865 - loss: 0.0647 - val_accuracy: 0.9615 - val_loss: 0.1345
Epoch 5/10
63/63 ━━━━━━━━━━━━━━━━━━━━ 263s 4s/step - accuracy: 0.9928 - loss: 0.0351 - val_accuracy: 0.9626 - val_loss: 0.1347
Epoch 6/10
63/63 ━━━━━━━━━━━━━━━━━━━━ 263s 4s/step - accuracy: 0.9956 - loss: 0.0243 - val_accuracy: 0.9592 - val_loss: 0.1612
Epoch 7/10
63/63 ━━━━━━━━━━━━━━━━━━━━ 261s 4s/step - accuracy: 0.9963 - loss: 0.0203 - val_accuracy: 0.9604 - val_loss: 0.1762
Epoch 8/10
63/63 ━━━━━━━━━━━━━━━━━━━━ 267s 4s/step - accuracy: 0.9977 - loss: 0.0104 - val_accuracy: 0.9502 - v

<h3 dir=rtl align=right style="line-height:200%;font-family:vazir;color:#0099cc">
<font face="vazir" color="#0099cc">
معیار ارزیابی
</font>
</h3>

<p dir=rtl style="direction: rtl; text-align: justify; line-height:200%; font-family:vazir; font-size:medium">
<font face="vazir" size=3>
هدف این است که مدل شما دسته‌بندی یک محصول را با دقت بالا پیش‌بینی کند، بنابراین در این پروژه از معیار  <code>Accuracy</code> جهت ارزیابی نتایج مدل شما استفاده خواهد شد.
</font>
</p>

In [ ]:
test

array([[  71,   33,   14, ...,  123,    0,    0],
       [ 111,   78,    6, ...,  757,    0,    0],
       [   2,   22, 4175, ...,    0,    0,    0],
       ...,
       [  27,    4, 2159, ...,  232,   76,   77],
       [  18,    6,    1, ...,   17,  487,  157],
       [   7,    6,   61, ...,   65, 3522,    0]])

In [57]:
# Evaluate

predictions = model.predict(test)
predictions

38/38 ━━━━━━━━━━━━━━━━━━━━ 16s 419ms/step


array([[1.71601187e-05, 1.87996250e-06, 2.13057137e-06, ...,
        5.41417867e-05, 9.98790264e-01, 5.42510243e-04],
       [8.55802282e-05, 4.43138561e-04, 6.32730462e-06, ...,
        1.33493959e-04, 4.34439607e-05, 2.82343244e-04],
       [1.15213215e-05, 9.33555057e-05, 5.74365782e-04, ...,
        9.17512716e-06, 1.88155377e-06, 3.99271948e-06],
       ...,
       [2.68908093e-06, 4.55358219e-07, 2.42440947e-05, ...,
        2.39152882e-06, 7.95997621e-05, 4.13593843e-05],
       [1.88569959e-06, 2.49078948e-05, 1.11132220e-04, ...,
        1.77601905e-05, 5.57651627e-04, 9.98758912e-01],
       [2.71126482e-05, 2.63658003e-04, 2.47525782e-06, ...,
        1.26886778e-04, 2.19982012e-05, 1.29227614e-04]], dtype=float32)

In [58]:
max_values = np.argmax(predictions, axis=1)
max_values

array([ 9,  7,  3, ...,  4, 10,  7])

In [59]:
# Preparing submission file
submission = pd.DataFrame(max_values, columns = ['cat_id'])
submission

,cat_id
0,9
1,7
2,3
3,10
4,2
...,...
1196,8
1197,0
1198,4
1199,10
